version: "3"
services:
  business:
    image: hans/business
    build: ./business
    environment:
      PORT: 8100
      INVENTORY_ADDRESS: inventory
      INVENTORY_PORT: 8200
      STORAGE_ADDRESS: storage
      STORAGE_PORT: 8300
    ports:
      - 8100:8100
    depends_on:
      - inventory
      - storage
    networks:
      - hasnet
  inventory:
    image: hans/inventory
    build: ./inventory
    environment:
      PORT: 8200
    networks:
      - hasnet
  storage:
    image: hans/storage
    build: ./storage
    depends_on:
      database:
        condition: service_healthy
    restart: always
    environment:
      PORT: 8300
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ADDRESS: database
      DB_PORT: 3306
      DB_NAME: hansdb
    networks:
      - hasnet
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: hansdb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - hasnet

networks:
  hasnet:
    driver: bridge